### ISSUE TITLE
Provide a way to pass Draft.js options to the Editor

### ISSUE THREAD

**Issue by andrerpena** [andrerpena/react-mde#126]

**Comment by andrerpena** [comment]
This should help with #90

**Comment by andrerpena** [comment]
You can now pass `draftEditorProps`

**Comment by ythecombinator** [comment]
Hey, @andrerpena! Is there any specific reason for you not to add this prop to `ReactMdeProps`?

**Comment by andrerpena** [comment]
Because there is no more Draft.js on v7. Adding Draft was a mistake. First because I was not using any rich text capability. Second because Facebook abandoned it. But thanks. You reminded me to put a warning there stating that while I work on the migration docs.

**Comment by ythecombinator** [comment]
Wow, that's news to me. I'm not that active on draft.js, where did they state that? Do you know if there are any specific reasons for abandoning the project? Ty

**Comment by andrerpena** [comment]
I have opdated the docs. Now you can pass textarea props instead of draftjs
props.

I'm also curious about why they did it. Facebook is super interest in rich
text editors, but my guess is that they did not find value in maintaining
features they don't need.

Humm. I just checked the repo and they are  back maintaining it. But
anyways, React me does not need it

**Comment by ythecombinator** [comment]
Thanks for the feedback, @andrerpena.

I know that this issue is probably not the best way to ask this but I'll throw the question anyways: given that you mentioned using draft.js was a design mistake and that you didn't take advantage of all its stuff, the first thing that comes to my mind is: how things like handling cursor position and text selection go now? Let me put a simple use case to illustrate my point: 

I had an application in production using v5 where the image upload recreated the exact behavior you have in Github editor (here's a video demo: https://cl.ly/b88a70ebaff4). To achieve that, I used both `DraftUtil` and `MarkdownUtil`; playing with guys `getMarkdownStateFromDraftState`, `insertText`, `buildNewDraftState` and so on. How would that be possible in v7? 

I see this may sound like a silly question but I admit it's sorta a huge mindshift for me to think of implementing something like this in a scenario where I don't have all that utils.

Does that make a little sense? Completely bananas? Any thoughts?
