### ISSUE TITLE
react-mde@6 cannot installed in yarn. 

### ISSUE THREAD

**Issue by weifuchuan** [andrerpena/react-mde#150]
`yarn add react-mde`

> error https://registry.npmjs.org/react-mde/-/react-mde-6.0.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, open 'C:\\Users\\fuchu\\AppData\\Local\\Yarn\\Cache\\v4\\npm-react-mde-6.0.0-13330accdc3e4ed210a3710f54aac6af14812146\\node_modules\\react-mde\\docs-md\\5.*-readme.md'"

The problem is unable to create file docs-md/5*-readme.md: Invalid argument.

**Comment by andrerpena** [comment]
I will check this today. Thanks for reporting!

**Comment by T0din** [comment]
Newbie here. I've tried to install it with yarn (and seemed to succed) but 
`import ReactMde from "../src";`
the import doesn't work. And i can't find any way around it. Not sure if related or not. Would love some help :)

**Comment by andrerpena** [comment]
@weifuchuan I was able to perfectly install react-mde from yarn.
@T0din , it is because the documentation was wrong. "../src" would only work because, in the demo, I load `readt-mde` locally. It would be `import ReactMde from "react-mde";`. I just changed the docs.

I'm setting up a repo to test installations. @weifuchuan , check this out. Yarn worked:
https://github.com/andrerpena/react-mde-test/tree/6.0.0

The demo in question is here:
https://github.com/andrerpena/react-mde-test/blob/6.0.0/src/App.js

I'm closing this issue. Please ping me if you need anything.

**Comment by jacklimwenjie** [comment]
This is still a problem for me. 
Upgrading to v7.0.3 solve the problem tho.
