### ISSUE TITLE
Write React unit tests

### ISSUE THREAD

**Issue by andrerpena** [andrerpena/react-mde#177]

**Comment by dcrtantuco** [comment]
I'll look into it!

**Comment by andrerpena** [comment]
Thanks @dcrtantuco !

**Comment by dcrtantuco** [comment]
@andrerpena hello sorry, I got busy, but I have the time to work on it now!
do you mind using @testing-library/react instead of enzyme?
I can revert it back if you don't want to, but I suggest giving it a try :)

I'll be working on this branch
https://github.com/dcrtantuco/react-mde/pull/1
Currently, I'm able to migrate to @testing-library and update current tests

**Comment by dcrtantuco** [comment]
I also notice the current script for running test uses mocha, but I can't seem to find any trace of mocha, I updated it to use jest

**Comment by andrerpena** [comment]
@dcrtantuco It's fine.

I never head of `react-testing-library` but OK, if you wrote the tests on it, it's fine. Let's merge it. And I really appreciate your effort

**Comment by andrerpena** [comment]
> I also notice the current script for running test uses mocha, but I can't seem to find any trace of mocha, I updated it to use jest

I would prefer jest over mocha these days
