### ISSUE TITLE
Keep resize grip for the preview mode too

### ISSUE THREAD

**Issue by tibetsprague** [andrerpena/react-mde#180]
I want the size of the editor to stay the same whether it is in edit or preview mode, and to keep the resize grip in both modes.

**Comment by andrerpena** [comment]
That is a very reasonable request, however, because of my limited capacity to work on this project, I decided to limit the scope of this project to what the Github editor provides and the way it works. The Github editor does not have this feature, so I am not willing to implement it. I would suggest you creating your own external react-mde editor and reuse the inner components, like the editor, preview and toolbar
