### ISSUE TITLE
add custom commands,also include default commands

### ISSUE THREAD

**Issue by deligent-ant** [andrerpena/react-mde#210]
in some case, I just want to add my custom command at the toolbar ，if I use commands props,i have to list all the default command。
```js
commands: [
          commands.orderedListCommand,
          commands.unorderedListCommand,
          commands.checkedListCommand,
          commands.imageCommand
]
```
so unfriendly. I just want to add one command ,do not change default.  so do the getIcons props， if i just want to change one icon,what should i do for the default icon.....???

**Comment by andrerpena** [comment]
I understand your pain, of having to re-add default commands manually. 
We can discuss an API that would be better. You need to not only be able to add a command but also to re-order and remove existing commands. The solution should be generic.

Maybe a less verbose way, would be to refer to default commands by name (string), instead of having to import them. Image "ordered-list" is a string recognized by react-mde, know you can say:

```
commands: ["ordered-list", [your custom command goes here]
```

Would that make it better? Do you have a better suggestion?

**Comment by deligent-ant** [comment]
thanks very much, i had solved it by your code
```js
import { getDefaultCommands } from 'react-mde/lib/js/commands'
import { SvgIcon } from 'react-mde/lib/js/icons'
```
by this wya, I can get the default command and icon,  i suggets dear author to display this api in the readme,so users can know it.
