### ISSUE TITLE
TextArea height to match content-height

### ISSUE THREAD

**Issue by phanatuan** [andrerpena/react-mde#229]
Hi @andrerpena , 

I am trying to make the following work: Removing the scrolling bar for the `textarea` input in tab "Write". However, there is no way for `textarea` to accept the css `max-height: max-content`. 

Is there a way to implement this built in? 

Thanks, 

Tuan

**Comment by andrerpena** [comment]
Hey @phanatuan . As I understand it, if you remove the scrollbar, this means you would want the height to auto-grow. Correct? There as a PR for that once, https://github.com/andrerpena/react-mde/pull/209, that unfortunately I rejected because, due to my limited time, I have to limit the scope of the editor.

I think the best solution would be you utilising the building blocks of ReactMde but implement your own outer component. This component https://github.com/andrerpena/react-mde/blob/master/src/components/ReactMde.tsx is a "relatively" thin layer on top of the topbar, editor and preview components.
