### ISSUE TITLE
Doesn't work with React 16

### ISSUE THREAD

**Issue by minjaitk** [andrerpena/react-mde#43]
Had my project on React 15.6, but when I tried updating to 16, this package broke with
```
Uncaught TypeError: Cannot read property 'node' of undefined
    at Object../node_modules/react-mde/lib/components/HeaderGroup.js (HeaderGroup.js:14)
    at __webpack_require__ (bootstrap 492c0abd2a0e9b4d876f:678)
    at fn (bootstrap 492c0abd2a0e9b4d876f:88)
    at Object../node_modules/react-mde/lib/ReactMde.js (ReactMde.js:21)
    at __webpack_require__ (bootstrap 492c0abd2a0e9b4d876f:678)
    at fn (bootstrap 492c0abd2a0e9b4d876f:88)
    at Object../node_modules/react-mde/lib/index.js (index.js:8)
    at __webpack_require__ (bootstrap 492c0abd2a0e9b4d876f:678)
    at fn (bootstrap 492c0abd2a0e9b4d876f:88)
    at Object.<anonymous> (bundle.js:170102)
```
I believe it's because PropTypes have been moved into a separate package.
Any chance of fixing it any time soon?

**Comment by andrerpena** [comment]
Thanks for reporting.. I'll take a look into it.

**Comment by andrerpena** [comment]
I just removed prop-types as a peerDependency. Please update to 1.0.2 and tell me if the problem continues

**Comment by minjaitk** [comment]
it seems that there have been a lot of changes, since I'm getting a lot of errors, and I need to change my code significantly (scss imports no longer work, I need to add showdown to the project, and it worked without it before etc.)
for example, 
```
ReactMdeCommands.getDefaultCommands is not a function
```
is there a list of all the changes?

**Comment by andrerpena** [comment]
Ohhhh... 

@minjaitk I'm so sorry. Because I wasn't maintaining the previous version this project and that I didn't know if many people were using it, I did not write a migration guide. =/

I recommend that you take a look at the Using section of the documentation: https://github.com/andrerpena/react-mde#using and compare with the way you use it.

The 3 major differences are:

- instead of using the `getDefaultCommands `, now I export the commands directly.
- The `textareaid` and `textareaname` props were replaced by `textAreaProps`.
- The paths of the CSS and SCSS have changed.

Please read https://github.com/andrerpena/react-mde/blob/master/readme.md and if you still have problems.. Don't hesitate to contact me. I'm closing this issue for now but feel free to re-open it.
