### ISSUE TITLE
Support for custom preview component

### ISSUE THREAD

**Issue by go1dfish** [andrerpena/react-mde#56]
Would be nice to be able to specify a custom component for previews in order to support customized markdown parsers.

**Comment by andrerpena** [comment]
This is a good idea.. I'll keep this open

**Comment by andrerpena** [comment]
I'll make this as part of an effort of decoupling the components and making `react-mde` more flexible:
Relevant thread: https://github.com/andrerpena/react-mde/issues/51

**Comment by andrerpena** [comment]
I'm now implementing the ability for your to select each command you'd like (https://github.com/andrerpena/react-mde/issues/58#issuecomment-346076435) , and right after that, I'll improve the composability of `react-mde`.

This is the next task in the queue.

**Comment by go1dfish** [comment]
Sweet.  We're looking at using this for https://github.com/decred/politeiagui and currently we use the Snudownd markdown parser and are likely to customize from there.

**Comment by andrerpena** [comment]
Thank you very much for considering using `react-mde` in your project.

After further consideration, I think the only way to make `react-mde` to support multiple previews is by breaking it down into 3 separate components and NPM packages (the toolbar, the textarea and a full-blown including the preview). This is because, even though I can strip `react-mde` in separate components in a single NPM package, the `peerDependence` to `showdown` will still be there. And having multiple NPM packages will complicate my life now.

I think I'll have to stick with `showdown` for now =/
