### ISSUE TITLE
Commands ... how to go about editing/creating them?

### ISSUE THREAD

**Issue by daanishnasir** [andrerpena/react-mde#57]
Everything works great with using the package, I'm just not sure how to go about editing the commands. 

I really need to take out the typing in code command and possibly the insert picture command. No need for it in my app for our users. 

Confused with the instructions of having to implement my own commands to do this (also not using typescript).

Seems like I would have create a file similar to that of ReactMdeCommands? That file looks like it needs imports from multiple different files. 

Any example of how to take out some of the default commands would be great!

**Comment by andrerpena** [comment]
Haha.. I was going to say that you got really lucky because all you had to do was to pick whatever commands you want from here: https://github.com/andrerpena/react-mde/blob/master/src/ReactMdeCommands.tsx

... and then I realized it's impossible. The only way to do it now is by excluding them by index from the resulting array.

Thanks for reporting. This is major issue. I'll create a new one and close this in favor of that.
