### ISSUE TITLE
Possibility for commands to return multiple times

### ISSUE THREAD

**Issue by markspolakovs** [andrerpena/react-mde#81]
Wishlist feature: make it possible for commands to update the text more than once, asynchronously.

Use case: image uploading. For example, when you first upload an image in the GitHub editor, it inserts `![Uploading IMG_20180214_172431_759.jpg…]()`. Once the upload is finished, it replaces the `Uploading...` text with the image's URL.

It is possible to work around this by using the command to insert the `Uploading`, and then updating `value` with the final URL, but this is messy and requires several layers of indirection.

**Comment by andrerpena** [comment]
This is actually a good idea and something I had in mind, because I want `React-Mde` to have all the features the GitHub editor has.

I'm adding this to the board now. The backlog list is ordered "desc" in priority. The ones at the top are going to be solved earlier.

Thanks for the suggestion and your support.

**Comment by markspolakovs** [comment]
For reference, in an earlier implementation of an editor (which I abandoned for react-mde), I did this by passing two callbacks into my command function (or my equivalent of the command function), one to get the current content (if it's changed between the initial command call and "now") and one to set it.

**Comment by andrerpena** [comment]
I see your point.

![image](https://user-images.githubusercontent.com/1581429/36951026-c0e82d3a-1ffe-11e8-9d44-1495c4cb3425.png)

![image](https://user-images.githubusercontent.com/1581429/36951044-f87c9312-1ffe-11e8-9f97-66b352d72a67.png)

I've posted screenshots to kind of test the behavior or GitHub. 

Yes. It would be much more scalable if the execute function was like this:

    execute: (getValue: () => Value, setValue: (value: Value) => void) => void;

GitHub allows you to keep typing while it's uploading the picture. I just made a test in which I pasted a image and then pressed backspace really quickly and if you're able to do it before the upload completes, it cancels it and doesn't change the text afterwards. This seems complicated to implement. Maybe we should just "lock" the editor and don't allow the user to type while the command is processing, but that would compromise the UX. Maybe this:

    execute: (getValue: () => Value, setValue: (value: Value) => void) => void | Promise<void>;

If a Promise is returned, then the editor is locked.

I'm not sure. What do you honestly think is better?

**Comment by markspolakovs** [comment]
I didn't know it did that. In my implementation I didn't bother with that - if the user backspaces out the image the upload is not cancelled - I can rely on the backend to delete orphaned files.

Locking could be a good idea, but I think it should be optional. How does this look:

```ts
export interface Command {
  type?: string;
  icon?: React.ReactNode;
  tooltip?: string;
  execute: (getValue: () => Value, setValue: (value: Value) => void) => Value | void | Promise<Value | void>;
  lockDuringExecution?: boolean;
}
```

**Comment by andrerpena** [comment]
@markspolakovs, excellent suggestion. Let's go for this then.

```
export interface Command {
  type?: string;
  icon?: React.ReactNode;
  tooltip?: string;
  execute?: (text: string, selection: TextSelection) => Value | Promise<Value>;
  executeAsync?: (getValue: () => Value, setValue: (value: Value => void, unlockEditor = false)) => void | Promise<void>;
  lockDuringExecution?: boolean;
}
```

I'll start working on this now.

**Comment by markspolakovs** [comment]
I'm just thinking... maybe, instead of `lockDuringExecution` on the command object. we can change the second parameter of `setValue` to `lockEditor` and make the implementer call it with `true` when they start, and `false` when their command is done. Means everything related to locking is in one place.

This is bikeshedding though, and the API above is perfectly fine.

**Comment by andrerpena** [comment]
@markspolakovs Interesting point. Now you can lock and unlock at will. Consider this the new API.
Thanks for your contribution.

**Comment by andrerpena** [comment]
@markspolakovs , unfurtunately I've decided to pause this until I investigate https://github.com/andrerpena/react-mde/issues/84, which I'll probably be able to complete until the end of this Sunday.

React-mde currently has a very big problem with state (Ctrl + Z after a command is executed), and we'll have another complicated problem to implement mentions and emoji the way GH does it, and Draft.js might be a solution for that.

I understand that Draft.js has a complicated API. What I'm investigating is the possibility to abstract that complexity away and have the commands to be implemented simply, exactly as we agreed upon, but without having to reimplement state management and whatever other complexity metions will bring.

I've decided to look into Draft before going into this because that might change the API a bit.

If you want, feel free to do this refactoring and send a PR, otherwise wait and I'll reply to this thread again on Sunday.

Thanks again for your contribution

**Comment by andrerpena** [comment]
Please check the new command API: https://github.com/andrerpena/react-mde/blob/master/src/types/Command.ts. Apart from locking the editor, it's there. I'll implement locking later. The 2 last callbacks of the Command are only for low-level Draft.js manipulation.

Draft.js also has support for pasting files. I'll expose that in the near future.

I believe that, in spite of the amout of breaking changes, this version has a much more capable API and I don't think I'll need to introduce any breaking change in the new future.

**Comment by lunalusy** [comment]
> @markspolakovs, excellent suggestion. Let's go for this then.
> 
> ```
> export interface Command {
>   type?: string;
>   icon?: React.ReactNode;
>   tooltip?: string;
>   execute?: (text: string, selection: TextSelection) => Value | Promise<Value>;
>   executeAsync?: (getValue: () => Value, setValue: (value: Value => void, unlockEditor = false)) => void | Promise<void>;
>   lockDuringExecution?: boolean;
> }
> ```
> 
> I'll start working on this now.

hi，Do you support toolip？
